-- 1.  DANH SACH CAC MAT HANG CO TAI CUA HANG

SELECT TENHANG FROM dbo.MATHANG


-- 2. CHO BIET DANH SACH CAC NHAN VIEN BAN HANG VAO NGAY 13-03
SELECT NV.MANV, TENNV
FROM dbo.NHANVIEN AS NV, dbo.HOADON AS HD
WHERE NV.MANV = HD.MANV AND NGAYHD = '2022-03-13'

-- 3. CHO BIET DANH SACH CAC MAT HANG DA BAN NGAY 13-03
SELECT DISTINCT MH.MAH, TENHANG
FROM dbo.MATHANG AS MH,dbo.HOADON AS HD, dbo.CTHOADON AS CTHD
WHERE MH.MAH = CTHD.MAH AND HD.SOHD = CTHD.SOHD AND NGAYHD = '2022-03-13'

-- 4. CHO BIET TONG SO LUONG CUA MOI MAT HANG BAN DUOC
SELECT MH.MAH, MH.TENHANG ,SUM(CTHD.SOLUONG) AS 'TONG BAN'
FROM dbo.CTHOADON AS CTHD, dbo.MATHANG AS MH
WHERE MH.MAH = CTHD.MAH
GROUP BY MH.MAH, MH.TENHANG

-- 5. CHO BIET TONG TIEN CUA HANG THU DUOC TU MOI MAT HANG
SELECT MH.MAH,MH.TENHANG ,SUM(SOLUONG) AS 'TONG SO LUONG',
	   DONGIA, SUM(DONGIA*SOLUONG) AS 'TONG TIEN'
FROM dbo.MATHANG AS MH, dbo.CTHOADON AS CTHD
WHERE MH.MAH = CTHD.MAH
GROUP BY MH.MAH, MH.TENHANG,DONGIA

-- 6. CHO BIET NHUNG MAT HANG CHUA CO AI MUA
SELECT MAH, TENHANG FROM dbo.MATHANG
WHERE MATHANG.MAH NOT IN 
(SELECT DISTINCT MAH FROM dbo.CTHOADON)

-- 7. NANG 10% LUONG CHO NHAN VIEN BAN NHIEU HON 5 MAT HANG
UPDATE NHANVIEN
SET LUONG = LUONG*1.1
WHERE MANV IN
(SELECT NV.MANV
FROM dbo.NHANVIEN AS NV, dbo.HOADON AS HD, dbo.CTHOADON AS CTHD
WHERE NV.MANV = HD.MANV AND HD.SOHD = CTHD.SOHD
GROUP BY NV.MANV, NV.TENNV HAVING COUNT(5) > 4)